name: asia_fibernet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+3

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.7.2
  flutter_localizations:
    sdk: flutter
  avatar_glow: ^3.0.1
  flutter_gen: ^5.11.0
  heroicons: ^0.11.0
  http: ^1.4.0
  #
  # internet_address: ^0.0.2
  network_info_plus: ^6.1.4
  get_ip_address: ^0.0.7
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  timezone: ^0.10.1
  location: ^8.0.1 # Optional, for reverse geocoding
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

  image_picker: ^1.0.4
  smooth_page_indicator: ^1.2.1
  flutter_animate: ^4.5.2
  flutter_local_notifications: ^19.4.0
  pinput: ^5.0.1
  confetti: ^0.8.0
  device_info_plus: ^11.5.0
  # flutter_native_timezone: ^2.0.0
  share_plus: ^11.0.0
  iconsax: ^0.0.8
  flutter_screenutil: ^5.9.3
  flutter_speedtest: ^0.0.3+3
  # workmanager: ^0.5.1
  flutter_foreground_task: ^9.1.0
  permission_handler: ^11.0.1
  flutter_secure_storage: ^8.0.0
  animate_do: ^4.2.0
  # background_locator_2: ^2.0.6
  # background_location: ^0.13.0
  font_awesome_flutter: ^10.9.1
  url_launcher: ^6.3.2
  pdf: ^3.11.3
  printing: ^5.14.2
  syncfusion_flutter_charts: ^30.2.7
  # intl: ^0.20.0
  badges: ^3.1.2
  lottie: ^3.0.0
  table_calendar: ^3.1.3
  webview_flutter: ^4.13.0
  flutter_pdfview: ^1.4.3
  file_picker: ^10.3.3
  mime: ^2.0.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  phone_state:  # Updated package
  circular_countdown_timer: ^0.2.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  mockito: ^5.4.4
  build_runner: ^2.4.8
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package




